jobs:
 - template: default.yml@templates
   parameters:
     minrust: 1.36.0 # alloc
     codecov_token: $(CODECOV_TOKEN_SECRET)
 - job: no_std
   dependsOn: []
   displayName: "Compile-check on no_std target"
   pool:
     vmImage: ubuntu-latest
   steps:
     - template: install-rust.yml@templates
       parameters:
         rust: nightly
         targets:
          - thumbv7m-none-eabi
     - bash: cargo check --target thumbv7m-none-eabi
       displayName: cargo check --target thumbv7m-none-eabi
 - job: features
   displayName: "Check feature combinations"
   pool:
     vmImage: ubuntu-latest
   steps:
     - template: install-rust.yml@templates
       parameters:
         rust: stable
     - script: cargo install cargo-hack
       displayName: install cargo-hack
     - script: cargo hack --feature-powerset check
       displayName: cargo hack
 - job: miri
   displayName: "Run miri on test suite"
   dependsOn: deny
   pool:
     vmImage: ubuntu-latest
   steps:
     - bash: |
         echo '##vso[task.setvariable variable=nightly]nightly-'$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
       displayName: "Determine latest miri nightly"
     - template: install-rust.yml@templates
       parameters:
         rust: $(nightly)
         components:
           - miri
     - script: cargo miri setup
       displayName: cargo miri setup
     - script: cargo miri test --features serde,raw -- -Zmiri-ignore-leaks
       displayName: cargo miri test

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.4
      endpoint: jonhoo
